### ISSUE TITLE
v4.4.0 Server issues

### ISSUE THREAD

**Issue by Quazerz** [TqLxQuanZ/DeceasedCraft#10]
I have a private server that was made when v4.2.5. was most recent. Then start updating the server version from there (kept the same world through these version). When I updated the server from v4.3.0 to v4.4.0 it started to have noticeable issues, like my friends not able to join and having error message viewed below:
![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/150748675/037909b1-4dae-4cc5-bc9f-afcc5b5cb30d)
![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/150748675/6b29eaf9-7308-419e-940a-bd25dba74917)

I tried redownloading the v4.4.0 server-pack and deleting the server configs(inside of the world folder) to regenerate. Also, when able to access to the server my health bar UI does not exist.

I checked if the world itself was corrupted and worked perfectly when downgrading the version.

I also I can't access the public beta server with the v4.4.0 version (if this helps)

**Comment by TqLxQuanZ** [comment]
Looking into this issue right now.

**Comment by TqLxQuanZ** [comment]
Send me the crash log if possible or server log.

**Comment by TqLxQuanZ** [comment]
Nevermind, figured out the issue, please update to v4.4.1.
