### ISSUE TITLE
Engineer´s Workbench crashing minecraft 

### ISSUE THREAD

**Issue by LuciBoop** [TqLxQuanZ/DeceasedCraft#110]
When I put a blueprint into the workbench (Immersive Engineering) my game will immediately crash. First it happened on our server running on the latest mod pack version. Everyone who will get too close to that workbench will crash aswell (as soon as the game tries to render it). After the deletion of the workbench, everything will revert to normal. I replicated the issus on a singleplayer world with same problem still present.

**Comment by LuciBoop** [comment]
Ok I found the problem why it is happening... If you turn off VBO inside of immersive engeering mod settings it will cause said crash... I turned this setting off (VBO) because of shaders not properly rendering some elements (windmills are invisible) I recommend to have it on or you will not be able use the engineering workbench.

**Comment by evgenyys12** [comment]
I have the same issue. I want to use the Engineer’s Workbench, but I also want shaders enabled and windmills to have visible textures. Does anyone know how this can be done?
