### ISSUE TITLE
Possible CPU or Memory(not sure about memory) Leak on Server

### ISSUE THREAD

**Issue by Quazerz** [TqLxQuanZ/DeceasedCraft#14]
Server, v4.4.4, running overnight, and woke up the next day it used all CPU usage on my server viewed below:

![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/150748675/2d22202b-b132-4f3e-b95e-53ab92ece5e2)

When checking the console it was spamming the line viewed below:

![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/150748675/386f8165-5a00-4534-bf0e-aca94e0dcae5)
This made it so I couldn't join the server for the following day.

Also when starting the server back up it would spam the line view below:

![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/150748675/8534f18f-86bd-4a0c-a8aa-4853aa5c501e)

Crash Logs: [crash-2023-11-21_08.54.13-server.txt](https://github.com/TqLxQuanZ/DeceasedCraft/files/13454884/crash-2023-11-21_08.54.13-server.txt)

**Comment by TqLxQuanZ** [comment]
It's probably the bees or beehives causing it try removing all of them see if it works. It exists in vanilla as well.
