### ISSUE TITLE
Modpack server-client compatibility

### ISSUE THREAD

**Issue by Nyphet** [TqLxQuanZ/DeceasedCraft#16]
Hello, I don't know it it's just me, but whenever I play with the modpack from client trying to connect to a server (same modpack version both sides) I get this red X for compatibility:
![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/65339023/b415fac7-26e0-4f70-8dc6-ad6e0146b2b3)
Of course I can still connect, but I was wondering if it was possible to add [Better Compatibility Checker](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker) so that the modpack version is checked instead of the Forge mod list.

**Comment by TqLxQuanZ** [comment]
Closing this as this is already added in upcoming patch 5.0.0
