### ISSUE TITLE
Colorful Health bar

### ISSUE THREAD

**Issue by Nyphet** [TqLxQuanZ/DeceasedCraft#17]
Sorry for opening many issues, these are mostly suggestions ahah
Like the overlaid armor points, what about adding [Colorful Health bar](https://www.curseforge.com/minecraft/mc-mods/colorful-health-bar) for overlaying health bars too rather than stacking one on top the other?

**Comment by Nyphet** [comment]
Also [Armor Points ++](https://www.curseforge.com/minecraft/mc-mods/armorpoints) can be a nice substitution for both mods, as it handles both armor and health bars.

**Comment by TqLxQuanZ** [comment]
Armor Points is a great mod, thanks for the suggestion, previously tested with Health Overlay but the health bar starts to act glitchy so I didn't add it in, this one seems stabler.
