### ISSUE TITLE
Updating Create makes CraftTweaker crash

### ISSUE THREAD

**Issue by AuraPhoenix1500** [TqLxQuanZ/DeceasedCraft#18]
Hey, I really love this modpack, but there is a bit of a problem.

Updating Create to version 0.5.0f causes CraftTweaker to just crash the game entirely, for some reason. It's a little bit annoying, especially because I went through all the trouble to create a cobblestone generator using the mod, only to find out that it doesn't even work properly on the version we have here.

It's not a major issue, just something I thought you should know for the next update. I'm very excited for it!

(Also I'd personally recommend adding the Snow Blocks—It's something that was in Quark in previous versions, but not in 1.18.2, which is also frustrating because snow bricks are like my favorite building blocks.

Anyway, I still love the modpack and will be eagerly waiting for the next major update~

**Comment by TqLxQuanZ** [comment]
By any means, you shouldn't update any mods in the modpack as some of the versions are incompatible with other mods.
Case closed.
