### ISSUE TITLE
Simple Planes Not Working

### ISSUE THREAD

**Issue by GovernorCockburnWanker** [TqLxQuanZ/DeceasedCraft#19]
For some reason the simple planes mod isn't working for me. I put the engine in the plane/helicopter but it simply doesn't work. I put fuel into the furnace engine but it doesn't start burning it. I've tried using the electric engine too. The battery won't charge when I'm logged in however when I relog it'll fill up. It won't run even on full charge.

**Comment by TqLxQuanZ** [comment]
Did you tried to throttle the plane speed up with [] bracket keys? Everyone is using the planes fine, you probably missed that.

**Comment by GovernorCockburnWanker** [comment]
yep entirely the issue lmaooo, thanks for the help!!!
