### ISSUE TITLE
Integrated package clearance is too easy - 整合包的困难太低了，能不能调整呢

### ISSUE THREAD

**Issue by trash-fish** [TqLxQuanZ/DeceasedCraft#20]
I don't really understand the refreshing of the monster, blood moon, corpse tide appears the mechanism, the early will be a lot, I built a good home, made a lot of defense measures found not to blood moon and corpse tide, then there is no difficulty, little skill, scavenge scavenge, this integration package graduated, just play a few days, the difficulty is too low, can not adjust the difficulty?

Early looting looting, go to the hospital to get a helmet, diamond is also easy to find, brush some special skills, go directly to the wasteland, build a home is not a corpse tide, graduated..

---------------

我不是很懂刷新怪、血月、尸潮出现的机制，前期会很多，我建造好了家，弄了很多防御措施发现不来血月和尸潮了，然后就没有什么难度了，点点技能，搜刮搜刮，这个整合包就毕业了，才玩了几天，难度太低了，不能调整难度吗？在游戏中设置了困难，没有很大的效果

前期搜刮搜刮，去趟医院搞个头盔，钻石也好找，刷点怪加技能，直接去荒地，建个家也没尸潮了，毕业了....

**Comment by TqLxQuanZ** [comment]
Next update should have more end game stuff, currently the modpack is still undergoing development.
