### ISSUE TITLE
How do I disable skill reset on death on my server

### ISSUE THREAD

**Issue by Cleanclover3711** [TqLxQuanZ/DeceasedCraft#22]
sorry this isn't a bug or anything but I went through all the configs I could find but couldn't find any related settings and this feature gets really annoying

**Comment by TheOneDal** [comment]
go to 
DeceasedCraft_Server_v4.4.6\world\serverconfig\betterleveling-gameplay.toml
edit:
	#If all progress should be lost on death
	resetOnDeath = true
in the .toml file
