### ISSUE TITLE
Crashing server when entering chunks with wasteland cities.

### ISSUE THREAD

**Issue by asesinoss** [TqLxQuanZ/DeceasedCraft#24]
I have a bug/issue. I have a server with my friends and when we try to enter wasteland cities it starts to lag very badly and the chunks are not loading. After that, it crashes. Please help me. Some things console is showing:  https://mclo.gs/HXmTZQi  (its the aternos server logs)

**Comment by TqLxQuanZ** [comment]
Pretty sure its the server is trying to generate new chunks and it just crashes because non-responding for too long.
