### ISSUE TITLE
The ordure mob generates infinite drops

### ISSUE THREAD

**Issue by JohnAppers** [TqLxQuanZ/DeceasedCraft#32]
The ordure mob from "THE UNDEAD REVAMPED" (the one that spawns in ceilings) seems to be conflicting with behaviours from the mod that makes zombies drop extra items. Each time the mob attacks with one of his fire balls, they explode and create a lot of string/bones/rotten flesh. 
The fire ball is probably counted as an entity and as such drops items when destroyed, or at least this is what I think is happening.

**Comment by TheOneDal** [comment]
oh wow i always thought its because they kept killing zombies that spawned in their area and it would just build up. I just tested this and its true.

**Comment by TqLxQuanZ** [comment]
Fixed in v5.0.0
