### ISSUE TITLE
Failed to Synchronize registry data from server

### ISSUE THREAD

**Issue by SonicDaBoi** [TqLxQuanZ/DeceasedCraft#38]
Failed to Synchronize registry data from server. I updated the Modpack to the latest version 5.0.3 and I can't connect to the server.
![DeceasedCraft 2024-03-08 10_57_51](https://github.com/TqLxQuanZ/DeceasedCraft/assets/74899407/26af2957-0536-4262-9123-63f4c4b1fcc6)

**Comment by TqLxQuanZ** [comment]
Is it a dedicated server you hosted through hosting services? If it is, which one is it?

**Comment by SonicDaBoi** [comment]
It's hosted through Aternos

**Comment by SonicDaBoi** [comment]
My issue summarized in one image: 

![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/74899407/94cb375d-9817-4955-8826-74a971641b31)

**Comment by TqLxQuanZ** [comment]
Have you tried do a clean wipe of the Aternos files and reinstall with 5.0.3?

**Comment by SonicDaBoi** [comment]
The server automatically updates but I'm willing to try. I'll start an new server and see if the issue is still there

**Comment by TqLxQuanZ** [comment]
Should be fixed in v5.0.4, wait for the release of it.

**Comment by SonicDaBoi** [comment]
Thank you, I made and started an new server but the issue still persisted. Let's see if the new version fixes it!

**Comment by SonicDaBoi** [comment]
It's solved now! Thank you very much
