### ISSUE TITLE
Skill tree root (combat) not available

### ISSUE THREAD

**Issue by TakutoTea** [TqLxQuanZ/DeceasedCraft#39]
As said, in V5.0.0 the skill tree for combat is unavailable.
![image_2024-03-08_151627738](https://github.com/TqLxQuanZ/DeceasedCraft/assets/162716146/6ac0af62-568f-47bd-8389-8dab85fe6653)
 is there something i can do or will it be patch?

**Comment by TqLxQuanZ** [comment]
Use the latest version.
