### ISSUE TITLE
Train tunnels are too small to fit any reasonable train

### ISSUE THREAD

**Issue by NovelPhacelia** [TqLxQuanZ/DeceasedCraft#4]
The train tunnels are too small to fit any reasonable trains. From the top of a bogey it only leaves 2 blocks to the roof for building, making it difficult to build any reasonable trains.

**Comment by TqLxQuanZ** [comment]
I'll need to double-check with the lost city rail generation if it's hard-locked to 6 blocks' height.
If it is, I can't really do anything about it.

**Comment by TqLxQuanZ** [comment]
This should be fixed in next update (4.0.0), as the railway are revamped with more space.
