### ISSUE TITLE
Create + Simple Planes Propeller Crafting Recipe Issue

### ISSUE THREAD

**Issue by Notgoodbob** [TqLxQuanZ/DeceasedCraft#41]
Hey! I've been enjoying DC a bunch - I've been wanting to start getting a fleet of planes set up and I'm having a hard time getting the crafting recipe for the propeller to work. I have the 13-block grid of mechanical crafters set up, and all the right components for the recipe, and it isn't wanting to create it. Is this user error, am I missing something?

Thank you!
![deceasedCraftCrafting](https://github.com/TqLxQuanZ/DeceasedCraft/assets/114518981/49bc9cd4-8928-469a-9e36-2a7e2db42eb5)

**Comment by TqLxQuanZ** [comment]
I can't remember if its you need a proper output that's not within center, so the item can be assembled and send out, but I could be wrong, might need to double check the recipe itself or the arrow leading to go out instead of center.

**Comment by Notgoodbob** [comment]
It does indeed need to go out instead of the center! Should've thought of that earlier. Thank you for your super quick response!
