### ISSUE TITLE
contenttweaker error?

### ISSUE THREAD

**Issue by dudtnwnd1234** [TqLxQuanZ/DeceasedCraft#42]
Hello Mod is really fun and I'm trying to open the server and enjoy it with my friends, but I can't connect even though contenttweaker mode is the same as server mode. What should I do in this case?
![캡처](https://github.com/TqLxQuanZ/DeceasedCraft/assets/163329814/39dd3cbd-cc19-45eb-8807-3d40c82c8095)

**Comment by TqLxQuanZ** [comment]
Either server or the player side has missing files, double check the files on hosting pack.

**Comment by dudtnwnd1234** [comment]
I checked again, but there were no missing files.

**Comment by TqLxQuanZ** [comment]
Did you perhaps add any new mods? And what version is this? does both client and server having same version as well?

**Comment by dudtnwnd1234** [comment]
It is version 1.18.2, and the server and client versions are the same. There are no additional modes added.

**Comment by TqLxQuanZ** [comment]
The version as in the modpack's version, I assume you're using server pack from curseforge as well right? If that's the case then I am not sure.
This error usually comes with the scripts folder inside are missing files, might want to double check the folder size of client and server see if there's any differences. If they are differences mean there are files are missing for one side.

**Comment by dudtnwnd1234** [comment]
I'm not sure because I used the server pack downloaded from curseforge.

**Comment by dudtnwnd1234** [comment]
I will check again and contact you. Thank you for your time.

**Comment by dudtnwnd1234** [comment]
I copied the mod from the server file and moved it to the Minecraft mods folder. Is it possible that an error occurred during this process?

**Comment by TheOneDal** [comment]
> I copied the mod from the server file and moved it to the Minecraft mods folder. Is it possible that an error occurred during this process?
From this comment, you make it sound like your not running the modpack from curseforge? and instead just copying the mods to a forge instance.

**Comment by dudtnwnd1234** [comment]
Oh i don't think that i'm sorry
