### ISSUE TITLE
[Suggestion] Immersive Aircraft

### ISSUE THREAD

**Issue by RedBlockCreator** [TqLxQuanZ/DeceasedCraft#43]
I see simple planes is in the pack, but immersive aircraft controls so much better/realistically. I would appreciate if it was added

**Comment by TqLxQuanZ** [comment]
No, Immersive Aircraft is not planned to add in anytime yet, because both mod functions the same and I'll need to spend more time to rebalance the other mod's plane as well which doesn't make sense either way.

**Comment by PSYCHOFOX81** [comment]
Damn-
