### ISSUE TITLE
Can’t complete several quests as the items for them are missing

### ISSUE THREAD

**Issue by Oyeo76** [TqLxQuanZ/DeceasedCraft#44]
The armor quests are not able to be completed because you can’t get the armor

**Comment by TqLxQuanZ** [comment]
Which armor? What version? Which armor quest? Please provide more information.
No one else has this issue as well.

**Comment by Oyeo76** [comment]
Never mind, one of the fps mods I added must of messed with the other mods, this was entirely my fault
