### ISSUE TITLE
"Server Closed" Error after couple of minutes playing.

### ISSUE THREAD

**Issue by Bashmash69** [TqLxQuanZ/DeceasedCraft#45]
Had a world that I've been playing for awhile and just recently its been kicking me out saying server closed/disconnect. I've checked and it says something about the Hordes mods table being "null" .The crash report is here: https://www.dropbox.com/scl/fi/e950jy1hakjzrz172fdpx/crash-2024-03-16_09.05.33-server.txt?rlkey=dtp2aqvd7uzmpz3bvx1tz0ijc&dl=0

**Comment by TqLxQuanZ** [comment]
Please always update the modpack to newest version before reporting the bug and see if it still happens. This bug is already fixed long ago.

**Comment by TqLxQuanZ** [comment]
And remember to delete the follow file when you update:
YOURMODPACKHERE\scripts\Mod\advanced_finders.zs

**Comment by Bashmash69** [comment]
I'm sorry I did not check to see if there is update. Thank you for your support

**Comment by TqLxQuanZ** [comment]
No worries, remember if you updated and the moment you join your world you see chat errors, please follow the step above.
