### ISSUE TITLE
Game crashes right as it loads up

### ISSUE THREAD

**Issue by Aerhtjiz** [TqLxQuanZ/DeceasedCraft#46]
https://www.dropbox.com/scl/fi/xfwc5cmyn4lzv9wiqrb09/crash-2024-03-16_13.43.28-client.txt?rlkey=zeef489idg3wzcxlmjbc7d4g1&dl=0

![Screenshot 2024-03-16 134411](https://github.com/TqLxQuanZ/DeceasedCraft/assets/117865514/0335d3c5-8444-4c78-8694-db35f16b5560)

![Screenshot 2024-03-16 134422](https://github.com/TqLxQuanZ/DeceasedCraft/assets/117865514/354e4455-01fa-4cfd-9d30-f07fe0d657fd)

**Comment by TqLxQuanZ** [comment]
reinstall the modpack, and make sure uses launcher to install, I am pretty sure there are some stuff didn't installed properly or corrupted files.
