### ISSUE TITLE
FTB Quests not working for server clients that aren't hosting

### ISSUE THREAD

**Issue by 1h4a** [TqLxQuanZ/DeceasedCraft#47]
Whenever a person joining a lan server tries to open FTB quests, the game immediately crashes. It doesn't happen in singleplayer.

Here is the crash log:
https://bytebin.lucko.me/1zFVcbqzPv

**Comment by TqLxQuanZ** [comment]
Can't do anything with this, its ftb quest's problem, playing with dedicated server is more appropriate.
