### ISSUE TITLE
Unable To Launch Server Version 5.2.2

### ISSUE THREAD

**Issue by DaddySaltine** [TqLxQuanZ/DeceasedCraft#49]
I had tried starting up a server with the provided files provided on this page here and I had moved all of the mods over from the pack itself into the server mods list, I would continue to get crashes and by looking at the logs I'm assuming it is caused by issues with having client side mods running on a server. I had tried to remove some of the client side mods that were reported in the errors on a previous install and I still couldn't get it to load. I have attached my crash report below. Thanks!
[crash-2024-03-20_06.42.46-fml.txt](https://github.com/TqLxQuanZ/DeceasedCraft/files/14666744/crash-2024-03-20_06.42.46-fml.txt)

**Comment by TqLxQuanZ** [comment]
Download the server pack properly from older version, newest version has slowest review process from CurseForge.
https://www.curseforge.com/minecraft/modpacks/deceasedcraft/files/all?page=1&pageSize=20
