### ISSUE TITLE
OPAC is not ready for the zombie apocolypse 

### ISSUE THREAD

**Issue by McKitten** [TqLxQuanZ/DeceasedCraft#50]
https://cdn.discordapp.com/attachments/603166851576496151/1220211998864969819/2024-03-21_14.26.11.png?ex=660e1dfa&is=65fba8fa&hm=6ea2fe9ec45c9123a86d7f29b6f34b1b2144e26c2fe8735f5b49eefed2e7b694&

https://cdn.discordapp.com/attachments/603166851576496151/1220233706732785734/2024-03-21_14.35.16.png?ex=660e3232&is=65fbbd32&hm=154fc2a9ef8aa831ce6015395a09d4e3e900513eed7e304fe38a5c1de740af94&

There is likely at least 2 other sites with holes in them but as you can see by the minimap the area is well and truly claimed, the first is actually within a force loaded area.

There is no setting in the config for this to be allowed to happen.

Might need to go back to FTB and hide its minimap (so it will only be accessible via inventory like teams/quests) behind journeymap, assuming there is a different outcome.

**Comment by TqLxQuanZ** [comment]
OPAC does not protect you from zombie invasion, be it explosion or mining zombies. You'll need to defend y our base properly.
