### ISSUE TITLE
I can't find the power button for the helicopter engine or the plane's simple plans.

### ISSUE THREAD

**Issue by MaikyYT1** [TqLxQuanZ/DeceasedCraft#51]
I have not found the power button for any of the planes or helicopters, I have already tried everything and nothing

**Comment by TheOneDal** [comment]
![Screenshot 2024-03-23 164006](https://github.com/TqLxQuanZ/DeceasedCraft/assets/120166356/92db7352-90f3-4cd5-b9ec-b271164e55c9)
![Screenshot 2024-03-23 164055](https://github.com/TqLxQuanZ/DeceasedCraft/assets/120166356/9c8d2514-5dbb-4a5f-911b-9fa2a689d424)
![Screenshot 2024-03-23 164109](https://github.com/TqLxQuanZ/DeceasedCraft/assets/120166356/d1289b43-af7b-4ac5-8182-34b6bbbf8982)
Please read the quest book, simple planes manual, and check your keybinds.

**Comment by TqLxQuanZ** [comment]
Closing this as it's already mentioned in questbook.
