### ISSUE TITLE
Issue with Crashes on Entering the Wasteland Server in Multiplayer Game on Centos Server, Game Version 5.2.3

### ISSUE THREAD

**Issue by trash-fish** [TqLxQuanZ/DeceasedCraft#53]
I am experiencing frequent crashes on a Centos server while playing a multiplayer game with game version 5.2.3. Specifically, the crashes often occur upon entering the wasteland server, particularly during the chunk loading phase.

[[234401] [Server threadERROR] [ne.m.txt](https://github.com/TqLxQuanZ/DeceasedCraft/files/14811419/234401.Server.threadERROR.ne.m.txt)
[crash-2024-03-30_17.47.52-server.txt](https://github.com/TqLxQuanZ/DeceasedCraft/files/14811420/crash-2024-03-30_17.47.52-server.txt)

**Comment by trash-fish** [comment]
Keep deleting, can't play

**Comment by trash-fish** [comment]
Server Config 24H32G，JDK17，JVM ConfigParams  -Xmx20G -Xms16G

**Comment by trash-fish** [comment]
server.properties：

#Minecraft server properties
#Sat Mar 30 17:50:13 CST 2024
allow-flight=true
allow-nether=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=hard
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
level-name=world
level-seed=
level-type=default
max-players=20
max-tick-time=60000000
max-world-size=29999984
motd=A Minecraft Server
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=false
query.port=8080
rate-limit=0
rcon.password=
rcon.port=25575
require-resource-pack=false
resource-pack=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=8080
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=12
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false

**Comment by TqLxQuanZ** [comment]
wtf is a fiahi.jar? Did you install anything other than the modpack's provided mods?

**Comment by trash-fish** [comment]
fiahi-1.2.4，IguanaTweaksReborn-2.12.12-mc1.18.2，[自动汉化更新] I18nUpdateMod-3.5.3-all




> wtf is a fiahi.jar? Did you install anything other than the modpack's provided mods?

Hello,

I am experiencing frequent crashes on a Centos server while playing a multiplayer game with game version 5.2.3. Specifically, the crashes often occur upon entering the wasteland server, especially during the chunk loading phase.

Additionally, we have integrated three mods into our server: 'fiahi-1.2.4' (a mod that causes food to spoil), 'IguanaTweaksReborn-2.12.12-mc1.18.2', and 'I18nUpdateMod-3.5.3-all' (for automatic Chinese translation updates).

Could these additions be contributing to the crashes? Any assistance or guidance in resolving this issue would be greatly appreciated.

**Comment by trash-fish** [comment]
Let's turn this off fiahi.jar，give a whirl

**Comment by TqLxQuanZ** [comment]
Any new mods that added in your end and result in crash is not in my field of fixing, the modpack is supposed to be played with those mods in it, no more no less.

If you encounter any crash with the mods you added on, you'll need to fix in yourself.
