### ISSUE TITLE
Carry On Bug?

### ISSUE THREAD

**Issue by gamediller** [TqLxQuanZ/DeceasedCraft#54]
![2024-04-01_00 48 22](https://github.com/TqLxQuanZ/DeceasedCraft/assets/165577199/eec6172a-367c-4674-b265-4ac13137a0c8)

![12312](https://github.com/TqLxQuanZ/DeceasedCraft/assets/165577199/7300f86e-8a63-4fbe-95c0-aa0f0df3ebd0)

Some mob i can Carry On

**Comment by TqLxQuanZ** [comment]
Because you're on creative mode?
