### ISSUE TITLE
Infinite Slowness

### ISSUE THREAD

**Issue by stivkis** [TqLxQuanZ/DeceasedCraft#55]
My friend ran into an issue while I'm away from home and I'm unable to access anything.

They told me they got an infinite slowness debuff that reappears on death and even after using milk. How do you fix this?

**Comment by stivkis** [comment]
![image-86](https://github.com/TqLxQuanZ/DeceasedCraft/assets/81774096/15340f67-9e61-4d0d-b473-f27b3bea659d)
Sure, it seems like normal slowness.
But once the timer reach end it reappears again.

**Comment by Tylerman119** [comment]
how did you fix it
