### ISSUE TITLE
SKlaucher (no premium) error of deceased craft

### ISSUE THREAD

**Issue by Merorex** [TqLxQuanZ/DeceasedCraft#56]
I wanted to play with my friend, everything was fine the first day, on the second day I mean today I couldn't play deceased craft, I get tons of errors, and I tried uploading the
ram allowed, downloading new java and deleting sklauncher and install it again, and nothing, at first it told me that I was missing mods now that textures of tac mod and minecraft itself are failing, help me I really want to play deceased craft with my friend (my pc has 8 GB of ram without graphics card, ntel(R) Core(TM) i7-3770 CPU @ 3.40GHz 3.40 GHz and 64 bits and no more 

failure code 
https://mclo.gs/ORIFb4Y

**Comment by TqLxQuanZ** [comment]
do a clean reinstall of the modpack

**Comment by Merorex** [comment]
I did that!!!

**Comment by TqLxQuanZ** [comment]
then I am not sure, I don't use that launcher and it seems like the installation process gone wrong for some reason.
Or it's just the ram is not enough, the modpack minimum requires 5gb of ram and your PC only has 8gb.
