### ISSUE TITLE
"Waiting for server" on create elevator action

### ISSUE THREAD

**Issue by Draza25** [TqLxQuanZ/DeceasedCraft#57]
![image_2024-04-02_164302154](https://github.com/TqLxQuanZ/DeceasedCraft/assets/105071066/29f39b9d-f6e5-4fc5-85ca-fc8921705c72)
![image_2024-04-02_164322715](https://github.com/TqLxQuanZ/DeceasedCraft/assets/105071066/4d27f5c2-bba3-41eb-9942-068efd311458)

I built an elevator in my underground base with the create mod (the 2nd one I have in this base)

Problem, when I interact with it (except to assemble or desassemble it) the game takes a long time to respond, the mode "the one probe" indicates "waiting for server" my game does not have a drop in performance. This lasts for about 30 seconds before the game freezes for about 20 seconds, after which the elevator does the requested action to bug again once it arrives at the requested floor. (Interaction made with either redstone contact or contraption controls) 

I didn't modify the modpack, I'm playing singleplayer on version 5.3.3 as said above, it's the second elevator I do with create, the first one works perfectly fine, I tried to restart my game several times, to undo and redo the elevator more or less big, nothing helps.

**Comment by TqLxQuanZ** [comment]
Or zip the world and upload it to gdrive then send it here.

**Comment by Draza25** [comment]
Of course, here is the link to the profiler ! https://spark.lucko.me/324u2WlMEi

For some reason the bug didn't happen again right away, I left the world only to come back right after, the elevator literally went through the floor, while the Redstone contact was still emitting Redstone (as if for the game, the elevator was still present?)

**Comment by TqLxQuanZ** [comment]
interesting, so does it still happen? and during the time it happen was it snowing?

**Comment by TqLxQuanZ** [comment]
Could you upload the world and send it to me so I can personally test it? it only happens after relog into the game? interesting

**Comment by Draza25** [comment]
Of course I have a bad connection, uploading it to my drive will take a bit of time, I will send another message with the link when it is finished

(Before I forget, my base is at these coordinates : 2950 100 -1200, the elevator concerned is the one in the base, currently, from the top to a future second floor, the first being the one that leads to the outside)

The first few times the bug was continuously present, now yes it only seems to appear when I log into the world

**Comment by Draza25** [comment]
Here's the drive link: https://drive.google.com/file/d/1Pqsouj_K7kHoYugEpzXH9FnIX0hpkWYV/view?usp=drive_link

**Comment by TqLxQuanZ** [comment]
I've requested access.

**Comment by TqLxQuanZ** [comment]
Alright thanks a lot, I'll be closing this issue and investigate the problem, for now it won't be affecting gameplay too much as long as you don't keep relogin.

**Comment by Draza25** [comment]
Thank you very much! I hope this can help 
Thank you also for the responsiveness ! ✨
