### ISSUE TITLE
Zombie Griefing

### ISSUE THREAD

**Issue by camthewheelchair** [TqLxQuanZ/DeceasedCraft#58]
I am trying to figure out how to disable Zombie Bombers from griefing. I've disabled zombie diggers but can't find where to disable bombers. (i don't care if it disables them all together or prevents griefing) 

I disabled griefing in the gamerules but nothing

**Comment by TheOneDal** [comment]
can see if deleting its entry in the json files in the incontrol folder works. Might break stuff?

**Comment by TqLxQuanZ** [comment]
Bombers aren't affected by mob griefing is an issue from zombie extreme mod itself, go report on the mod itself not here.
