### ISSUE TITLE
"I don't know how to use the Game Item Mutation Essence"

### ISSUE THREAD

**Issue by trash-fish** [TqLxQuanZ/DeceasedCraft#59]
![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/70623599/1f6a1cfd-a582-49a3-a4fa-e42226cff927)
"I don't know how to use the Game Item Mutation Essence"

**Comment by TqLxQuanZ** [comment]
Do you even read the questbook information for mutagen serum in Seeking The Cure quest?

**Comment by trash-fish** [comment]
I read that it says to go to the Wasteland and use the cure for mutant creatures But it doesn't work.

**Comment by TqLxQuanZ** [comment]
it's only used to cure mutant "animals".
