### ISSUE TITLE
Mobs won’t spawn 

### ISSUE THREAD

**Issue by Itsrylee** [TqLxQuanZ/DeceasedCraft#6]
Hello, 

I really wanna play this mod I’ve downloaded it followed all the instructions but for some reason zombies won’t spawn at all the spawners don’t work, I’ve fiddled about with the settings but nothing is working :(

**Comment by Itsrylee** [comment]
Thank you just realised lol didn’t spend enough time on it to figure it
out, having loads of fun now haha

**Comment by TqLxQuanZ** [comment]
That's good to hear, closing the ticket now.
