### ISSUE TITLE
Zombies spawning indoors in bright spaces

### ISSUE THREAD

**Issue by Scivirino** [TqLxQuanZ/DeceasedCraft#61]
Seems to be an issue, I dont know if its tied into a mod or anything but when I host it zombies just seem to be able to spawn indoors regardless of the situation even sometimes it happens within player line of sight and they spawn 2 blocks away. Is there a fix for this?

**Comment by TqLxQuanZ** [comment]
Either it is a horde building didn't not get cleared properly or light level not high enough, zombies spawn below 3 light levels.
