### ISSUE TITLE
Server crash on world generating

### ISSUE THREAD

**Issue by GreenChiip** [TqLxQuanZ/DeceasedCraft#62]
Game and server keeps crashing when rendering new chunks.
Seems to be more often in citys, but  not realy ?

Crash repport: https://pastebin.com/9vSDBPb9 
Password: 1234 

Server specs:
Debian 12 x86_64
CPU: AMD Ryzon Threadripper 1950x (32) @ 3.400GHz
GPU: AMD ATI Radeon RX 470/480/570/570X580/580X/590
Memory: 12GB

**Comment by TheOneDal** [comment]
you have 3gb allocated?

**Comment by GreenChiip** [comment]
The server has 12gb, and the crash can happen at 4gb usage  or at 8gb. The memory should not be the problem.

**Comment by TheOneDal** [comment]
it would be some thing to look at if had 3 allocated 💀. Does it crash when your generating chunks in person or when your using chunky? If you press spam enter in the console while its happening does it respond.

**Comment by GreenChiip** [comment]
The console freezes and any commands are delayed from 1sec to 2-3min or the server just says good night and crashes.

**Comment by TheOneDal** [comment]
sounds like just chunky generation being too taxing, use chunky to generate the chunks your going to explore beforehand.

**Comment by GreenChiip** [comment]
Looks like Chunky works fine from the console.
Running a little bit behind but it keeps up!
Thanks for the tip 👍🏼
