### ISSUE TITLE
Server crash on chicken laying egg.

### ISSUE THREAD

**Issue by FyreFoxUwU** [TqLxQuanZ/DeceasedCraft#64]
Having a strange issue on a server we're hosting through Nitrado, where when a chicken we have in the base, lays an egg the server crashes. We have tried removing and respawning the chicken but it still crashes. 

Crash log : [crash-2024-04-09_04.41.40-server.txt](https://github.com/TqLxQuanZ/DeceasedCraft/files/14913564/crash-2024-04-09_04.41.40-server.txt)

**Comment by TqLxQuanZ** [comment]
Could you zip the world and send it to me? It is a strange issue.

**Comment by FyreFoxUwU** [comment]
Sure, the coords are -349 64 -1494. Opened the world in single player and chickens are laying eggs fine without a crash. 

Had to upload the world to GDrive as was over the Github limit https://drive.google.com/file/d/12FO8mYxcHDtitIB54lXPuqd6DYLfcgDE/view?usp=sharing

**Comment by TqLxQuanZ** [comment]
I'll take a look at it over the weekend, busy with stuff, the current fix I can think of is to delete the entities \world\entities folder but it'll delete every entity in the game unless you know which chunk u're at.

**Comment by FyreFoxUwU** [comment]
No worries, I'll test that out and see it if works. Thanks

**Comment by TqLxQuanZ** [comment]
What version is this? I teleported to the target location but it didn't crash on the server.

**Comment by TqLxQuanZ** [comment]
Fixed in 5.3.6, there is some issue from chicken laying egg, not sure why VMH mod caused it, for now the chicken will be automatically deleted by neruina mod.
