### ISSUE TITLE
G-portal isues

### ISSUE THREAD

**Issue by C6Ranger** [TqLxQuanZ/DeceasedCraft#67]
I was trying to get a server set up through G-portal to play this modpack with friends. However the server continually failed to start. I switched to another modpack to troubleshoot and that one started fine. After talking with a support staffmember. they told me that there was a mod within the pack that was causing the issue but the failed to tell me which one. Any idea what the issue might be? I'm sorry I couldn't give more detail.

**Comment by C6Ranger** [comment]
This was the log for the error

07:56:55] [main/WARN] [CanaryConfig/]: Mod 'pluto' attempted to override option 'mixin.world.player_chunk_tick', which doesn't exist, ignoring
[Serene Seasons Transformer]: Transforming m_8714_ (Lnet/minecraft/world/level/chunk/LevelChunk;I)V in

**Comment by TheOneDal** [comment]
Send the entire log. This warning was ignored and shouldn't cause issues.

**Comment by C6Ranger** [comment]
I will try to get it. It was provided to me by the support staff of G-portal

**Comment by TqLxQuanZ** [comment]
Pretty sure the server pack missing some files, otherwise it's hosting website has some security weird issue that the modpack file didn't fully downloaded.
