### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by Glitched8Giant** [TqLxQuanZ/DeceasedCraft#68]
I'm trying to set up this armorset so we could use it in the wasteland without taking damage all the immunization effects work but for some reason we still take damage if were near the wasteland area. Am I missing a keyword or something please help.

[T51.json](https://github.com/TqLxQuanZ/DeceasedCraft/files/14945161/T51.json)

**Comment by TheOneDal** [comment]
are you overheating?

**Comment by Glitched8Giant** [comment]
> are you overheating?

Its saying that "Do not enter the wasteland without gasmask"

**Comment by TheOneDal** [comment]
try adding the your helmet to helmet_radiation.json

**Comment by TqLxQuanZ** [comment]
I am closing this because this is straight out out of the modpack's managing side due to it is a mod that does not belong to the modpack.
