### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by HoloSmoke** [TqLxQuanZ/DeceasedCraft#7]
After getting the "mutagene infection" debuff and killing a mob I wasn't able to break a single block and all of the mobs will disappear, I solved the problem by logging out out and then back in the game, but even without the debuff the problem still persist after killing a mob, all of this after discovering the wasteland biome and encountering the mutated zombie.

If something is not clear in english is because is not my first leanguage.
Fell free to message me on my instagram since I love this modpack and I think it will become the best survival zombie modpack <3

My Instagram is alessio.giampaoli

**Comment by HoloSmoke** [comment]
[crash-2023-10-31_14.08.14-server.txt](https://github.com/TqLxQuanZ/DeceasedCraft/files/13216728/crash-2023-10-31_14.08.14-server.txt)

here's the crash report

**Comment by TqLxQuanZ** [comment]
This is an issue caused from mutationcraft, you'll need to head to world/data/mutationcraft_worldvar.dat and delete the mutationcraft_worldvar.dat file, once deleted, the server will work fine again, remember to restart.
