### ISSUE TITLE
Game crash when opening MrCrayfish's Gun Mod's workbench

### ISSUE THREAD

**Issue by illogicaliam** [TqLxQuanZ/DeceasedCraft#74]
Opening the workbench of MrCrayfish's Gun Mod results in an instant crash. Since there are two separate gun mods in the modpack I tried removing TAC, but it also removed some key features like the skill tree. Reinstallation also results in a crash.

Steps to reproduce:
- Launch Minecraft w/ Prism Launcher
- Open MCGM's workbench
- Client crash

Log:
[crash-2024-04-17_12.40.46-client.txt](https://github.com/TqLxQuanZ/DeceasedCraft/files/15014653/crash-2024-04-17_12.40.46-client.txt)

**Comment by Mygnol** [comment]
MrCrayfish's Gun Mod is a dependency of TAC, and neither can be removed without causing issues with the modpack. The workbench is disabled in survival and is unobtainable, please use TAC's workbench instead.

**Comment by illogicaliam** [comment]
Oh okay sorry, I had no idea it was unobtainable since a friend in our LAN world had put it down, I guess he had gotten it with cheats. I'm sorry for opening this thread since the answer was this simple. Thanks again!
