### ISSUE TITLE
TAC skins not changing gun model

### ISSUE THREAD

**Issue by JDaf12** [TqLxQuanZ/DeceasedCraft#76]
I might have missed something, but I tried applying color skins to TAC guns that support it, like the Scar H. When I place the color skin I want in the skin slot of the gun's attachment GUI it doesn't show up on the gun model.

**Comment by TheOneDal** [comment]
Has been disabled by tac themselfs. Something about moving to new system

**Comment by JDaf12** [comment]
Ohh, Ok thank you!
