### ISSUE TITLE
VMH and Chickens

### ISSUE THREAD

**Issue by shawnbucholtz** [TqLxQuanZ/DeceasedCraft#79]
I am really enjoying this mod pack but I was not satisfied that chicken eggs were not stacking.

Upon some research it is because VMH scale chicken eggs was set to true which adds a bunch of NBT data to each egg.  If you piped your egg farm into RS the game's going to overload a chunk with NBT. To solve this I set `vmhScaleEggs` to false which stopped the NBT from being added to eggs.

However this seems to cause another (related?) issue with a vmh function that is trying to access a negative array index which of course causes the JRE to crash.

I do not know if I should create the issue here or there, and whether something like this is fixable via another mod or newer version of the vmh mod?  I see an earlier issue about chicken eggs was fixed by adding another mod, but I don't think this is quite the same scenario.

[crash-2024-04-21_19.58.18-server.txt](https://github.com/TqLxQuanZ/DeceasedCraft/files/15066687/crash-2024-04-21_19.58.18-server.txt)

**Comment by TqLxQuanZ** [comment]
It is an issue from VMH, the best I can do is that re-enable vmhScaleEggs and making the egg unstackable because disabling that cause chicken laying egg crash, unless you're able to find a mod disabling chicken laying egg.
