### ISSUE TITLE
Some crops don't give XP

### ISSUE THREAD

**Issue by Nyphet** [TqLxQuanZ/DeceasedCraft#8]
Hello, I love you modpack, it's very well done and immersive!

I noticed that some crops, for example Hemp from Immersive Engineering and Rice from Farmer's Delight, don't give xp when harvested.  
I don't know if it's due to the mod used to allow right-click harvest.  
However, this instead surely depends on the current right-click harvest mod, when harvesting in such way a crop with a block in hand, the block annoyingly gets placed every time.

May I suggest using my mod, [Harvest With Ease](https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease), to handle the right-click harvest? It also allows to drop xp, like the current one does, and you can also configure it to require a hoe in hand to allow right-click harvest. Furthermore, I tested it with the aforementioned other 2 mods, and it works just fine! It also gets rid of the block-placing thing when harvesting.

**Comment by TqLxQuanZ** [comment]
I'll look into this and possibly add it in the next patch.

**Comment by TqLxQuanZ** [comment]
Added in v5.0.0.
