### ISSUE TITLE
Pufferfish skills configuration not loading

### ISSUE THREAD

**Issue by big-poppy** [TqLxQuanZ/DeceasedCraft#80]
An issue I noticed that I haven't before is my game not loading pufferfish's skills. It seems has to be some sort of issue with the configuration file. I attached the log below, let me know if there is anything else I can provide that might help!

[latest.log](https://github.com/TqLxQuanZ/DeceasedCraft/files/15067344/latest.log)

**Comment by TqLxQuanZ** [comment]
did you just remove zombie mobs for no reason? please do not never, ever remove any mod from the modpack since it breaks stuff.

**Comment by big-poppy** [comment]
No I did not remove that mod, was it missing for some reason? The only mod I disabled was physics mod because my PC would not load the pack with that mod loaded. As for the "Zombie Mobs" mod, I did not remove that, but I'll add it back in and see how that fixes things.

**Comment by big-poppy** [comment]
Yeah, just added the mod in and it works great! I am playing on the Prism Launcher and I have since learned that it does not register certain mods as having version specific downloads, Nocube's Zombie Mobs being one of them. Appreciate the help!
