### ISSUE TITLE
How do you build the server version from this repo ?

### ISSUE THREAD

**Issue by Spokeek** [TqLxQuanZ/DeceasedCraft#81]
Maybe i'm being dumb, not knowing how forge server works nowdays, but simply by following the readme instructions, i end up with a raw 1.18.2 forge server with no mods reloaded.
I followed the following instructions:

- Download latest version of the repo from the main branch as zip
- Extract in a folder
- Run the "Forge Installer" jar
- Use the "install server" option selecting the extracted folder
- Launch server with provided bat file
- Accept Eula
- Relaunch bat file

Did i miss something ?

Also, used Windows 10 with OpenJDK 17.0.7

**Comment by TqLxQuanZ** [comment]
Download the server pack from
https://www.curseforge.com/minecraft/modpacks/deceasedcraft/files/all?page=1&pageSize=20
5.4.6 is not yet finished review so you can't download it, you can get older versions.

**Comment by Spokeek** [comment]
> Download the server pack from https://www.curseforge.com/minecraft/modpacks/deceasedcraft/files/all?page=1&pageSize=20 5.4.6 is not yet finished review so you can't download it, you can get older versions.

I know that, but for that same reason, is there a way to build a server version from your public repository ?

**Comment by TqLxQuanZ** [comment]
No, because the mods aren't submitted in the repository and they're too large.

**Comment by Spokeek** [comment]
Gotcha
