### ISSUE TITLE
Laboratory is getting completely destroyed while exploring

### ISSUE THREAD

**Issue by JohnnyDark7** [TqLxQuanZ/DeceasedCraft#84]
Mob spawning in laboratory is insane. I still don't even know what keeps spawning them, but that's not the main problem. There are too much zombies with pickaxes and cloggers which completely wrecks laboratory while you try to get down. And in the end there is no keycard chest at the bottom floor because there is nothing left from bottom floor except portal frame. And it's quite impossible to run to the bottom floor to get keycard before it gets blown because of quantity of enemies + lagging from insane amount of mobs. Mob griefing gamerule don't change anything. This is so unfun to deal with, it would be good if at least chest with keycard would have been indestructible

**Comment by TqLxQuanZ** [comment]
This is an oversight, clogger shouldn't be spawn at the bottom floor but it seems to do so, most likely a bug, should be fixed in the next version.

**Comment by TqLxQuanZ** [comment]
Fixed in v5.4.9, cloggers now only spawn in surface.
As for zombie spawning issue in laboratory, it's always the horde building or light level.
