### ISSUE TITLE
Immersive Petroleum

### ISSUE THREAD

**Issue by IdrisZuzer** [TqLxQuanZ/DeceasedCraft#87]
Immersive Petroleum mod can't find Crude oil, used a Drill sample on 100+ plus chunks and I can only see minerals and no reservoirs in the sample I have searched for 3hr+ and even used commands to find crude oil but can't find it, is crude oil disable in immersive petroleum? how do I start to make polythene to make high-carbon steel alloy?

**Comment by TqLxQuanZ** [comment]
Read the questbook again, but slowly.

**Comment by IdrisZuzer** [comment]
ok, that was stupid of me and Thank you for the quick reply enjoying the pack thoroughly, The loot goblin in me just loves mod packs like these.
