### ISSUE TITLE
Infection effect causes mass frame drops

### ISSUE THREAD

**Issue by igniter16** [TqLxQuanZ/DeceasedCraft#89]
When playing normally i get consistently good frames, yet when i get infected, my frames drop to 12 until the effect is gone. this makes it very hard to deal with the wasteland and hordes. 

This has happened since i started playing in version 5.4.7 and has persisted through each update, i am now on the latest 5.4.11

![2024-04-29_15 53 51](https://github.com/TqLxQuanZ/DeceasedCraft/assets/111385533/af41cc75-d93a-46b4-a64c-7c035ec2b4f6)
![2024-04-29_15 59 14](https://github.com/TqLxQuanZ/DeceasedCraft/assets/111385533/ea7f38e0-035d-458f-b40e-3ab9e84cfefb)

**Comment by rixls** [comment]
I think this started when Hordes was updated in 5.4.6

**Comment by TqLxQuanZ** [comment]
Will be fixed in 5.4.13
