### ISSUE TITLE
mob wont spawn and no map available

### ISSUE THREAD

**Issue by OuDayas** [TqLxQuanZ/DeceasedCraft#9]
After I iinstalled the modpack, the mob wont spawn, and sometime the generated mao, some areas randomly crashes the game, and I don-t know where to find the @default@ map from images

**Comment by TqLxQuanZ** [comment]
First day mob doesn't spawn, u need to make sure the cities profile is set to deceasedCraft, and what did you install the modpack with? Sounds like the launcher didn't fully help u install or something went wrong, try clean reinstall again.

**Comment by OuDayas** [comment]
> First day mob doesn't spawn, u need to make sure the cities profile is set to deceasedCraft, and what did you install the modpack with? Sounds like the launcher didn't fully help u install or something went wrong, try clean reinstall again.

I used curse, i just tryied to create a new world, without change any settings, the mobs in that world, doesn't spawn even after more days, idk why

**Comment by OuDayas** [comment]
> First day mob doesn't spawn, u need to make sure the cities profile is set to deceasedCraft, and what did you install the modpack with? Sounds like the launcher didn't fully help u install or something went wrong, try clean reinstall again.

I fixed, idk how, but I have a mob whos invisible, idk if is normal, its the crackler from undead revamp2, and how can I kill him?

**Comment by TqLxQuanZ** [comment]
I think you might need to do a clean reinstall on the modpack, some files are properly not being readed through. The crackler shouldn't be spawning at all.
