### ISSUE TITLE
Lead ore no where to be found

### ISSUE THREAD

**Issue by LucEnden** [TqLxQuanZ/DeceasedCraft#91]
I've seen multiple people online, including myself, stating they cant for the live of them find any lead! I also could not find any statement made that this is intentional.

So, is the lead ore generation an issue or is this intentional?

**Comment by GoldenMaster8** [comment]
Lead is found most commonly between y80 to y8 in open caves, it's not really a problem with the pack more so a feature of the Immersive Engineering mod. If you find caves that are around that level you should find plenty of lead. You can also use a drill machine from immersive with an excavator

**Comment by LucEnden** [comment]
> Lead is found most commonly between y80 to y8 in open caves, it's not really a problem with the pack more so a feature of the Immersive Engineering mod. If you find caves that are around that level you should find plenty of lead. You can also use a drill machine from immersive with an excavator

I will be testing this afternoon, will report back shortly

**Comment by LucEnden** [comment]
I can confirm this, closing the issue
