### ISSUE TITLE
Hordes come on a loop every night after 15 days of play time

### ISSUE THREAD

**Issue by AntounMarc** [TqLxQuanZ/DeceasedCraft#96]
The modpack is amazing and has a lot of very cool features, thank you for the hard work you put into it. But for some strange reason when i load up the world the first 15 days go by regularly but after the first horde night comes, every night after that is a horde night as well, i can't sleep through the night, i can't leave the area near my base where i set up my defenses the only thing i can do is keep switching between hard and peaceful whenever a horde happens not on schedule. is there any way to fix this?

PS: i have learned about this modpack from watching CaptainSparklez on youtube and I am avoiding what caused him troubles which is loading different saves in one instance of game launch but that has not solved the issue.

**Comment by TqLxQuanZ** [comment]
What version? Use latest version if you're at older version.
